application:
  kafka:
    topic: "topic"

spring:
  application:
    name: mail-service

  kafka:
    producer:
      bootstrap-servers: "127.0.0.1:29092"
      client-id: "producer"
    consumer:
      bootstrap-servers: "127.0.0.1:29092"
      client-id: "consumer"
      group-id: "mail-group"
      auto-offset-reset: earliest

