application:
  kafka:
    topic: "topic"

spring:
  application:
    name: mail-service
  mail:
    host: smtp.yandex.ru
    port: 465
    username: "forestofhabits@yandex.ru"
    password: "ffpngulbauxsgifh"
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          starttls:
            enable: true
          auth: true
#        debug: true

  kafka:
    bootstrap-servers: "185.50.202.250:29092"
    producer:
      bootstrap-servers: "185.50.202.250:29092"
      client-id: "producer"
    consumer:
      bootstrap-servers: "185.50.202.250:29092"
      client-id: "consumer"
      group-id: "mail-group"
      auto-offset-reset: earliest

